using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace InventoryServices
{
    [MetadataType(typeof(CategoryAnnotations))]
    public partial class Category
    {
        // Note this class has nothing in it.
        // It's just here to add the data annotaions to EF model class Category.cs generated by EF scaffolding process.
        // This approach prevents the data annotations from being overwritten when 
        // we update the model classes from database using ‘Update Model from database’ option in visual studio.
    }

    [MetadataType(typeof(ProductAnnotations))]
    public partial class Product
    {
        // Note this class has nothing in it.
        // It's just here to add the data annotaions to EF model class Category.cs generated by EF scaffolding process.
        // This approach prevents the data annotations from being overwritten when 
        // we update the model classes from database using ‘Update Model from database’ option in visual studio.
    }

    public class CategoryAnnotations
    {
        public int CategoryId { get; set; }

        [MinLength(2, ErrorMessage = "Minimum 2 chars required")]
        public string CategoryName { get; set; }

        public string CategoryDescription { get; set; }
    }

    public class ProductAnnotations
    {
        public int ProductId { get; set; }
        [MinLength(2, ErrorMessage = "Minimum 2 chars required")]
        public string ProductName { get; set; }
        public int CategoryId { get; set; }
        public decimal Price { get; set; }
        public string Currency { get; set; }
        public int UnitId { get; set; }
        public string ProductDescription { get; set; }
    }
}